export type Role = 'admin' | 'manager' | 'technician' | 'collection-agent' | 'data-entry' | 'viewer';

export const ROLES_PERMISSIONS = {
  admin: [
    { module: 'billing', action: 'view' },
    { module: 'billing', action: 'edit' },
    { module: 'bills', action: 'view' },
    { module: 'bills', action: 'edit' },
    { module: 'patients', action: 'view' },
    { module: 'patients', action: 'edit' },
    { module: 'packages', action: 'view' },
    { module: 'packages', action: 'edit' },
    { module: 'reports', action: 'view' },
    { module: 'reports', action: 'edit' },
    { module: 'tests', action: 'view' },
    { module: 'tests', action: 'edit' },
    { module: 'doctors', action: 'view' },
    { module: 'doctors', action: 'edit' },
    { module: 'users', action: 'view' },
    { module: 'users', action: 'edit' },
    { module: 'statistics', action: 'view' },
    { module: 'statistics', action: 'edit' },
    { module: 'subscription', action: 'view' },
    { module: 'subscription', action: 'edit' },
    { module: 'collection-centers', action: 'view' },
    { module: 'collection-centers', action: 'edit' },
  ],
  manager: [
    { module: 'billing', action: 'view' },
    { module: 'bills', action: 'view' },
    { module: 'patients', action: 'view' },
    { module: 'packages', action: 'view' },
    { module: 'reports', action: 'view' },
    { module: 'tests', action: 'view' },
    { module: 'doctors', action: 'view' },
    { module: 'users', action: 'view' },
    { module: 'statistics', action: 'view' },
  ],
  technician: [
    { module: 'reports', action: 'view' },
    { module: 'reports', action: 'edit' },
    { module: 'tests', action: 'view' },
  ],
  'collection-agent': [{ module: 'bills', action: 'view' }],
  'data-entry': [
    { module: 'billing', action: 'view' },
    { module: 'bills', action: 'view' },
    { module: 'patients', action: 'view' },
  ],
  viewer: [{ module: 'reports', action: 'view' }],
};
